### ISSUE TITLE
Remove Exodus output from transaction? 

### ISSUE THREAD

**Issue by cassc** [OmniLayer/OmniJ#157] opened 2018-12-23 12:48 UTC
Hi, 

Thanks for your great work!

I am trying to use OmniTxBuilder#createSignedSimpleSend to create USDT transaction. What I found is that the generated transactions has an output which sent a small amount of bitcoin to exodus address:   1EXoDusjGwvnjZUyKkxZ4UHEf77z6A5S4P 

Should I remove this output from my transaction and how to achieve this with omnij?

**Comment by msgilligan** [comment] 2019-01-07 10:03
I believe the Exodus output is required for [Class B]() transactions. OmniJ [needs to implement Class C transactions](https://github.com/OmniLayer/OmniJ/issues/120) and the Exodus output _may_ not exist in Class C transactions. @dexX7 is that true?

**Comment by dexX7** [comment] 2019-01-08 17:47
Hey @cassc,

the output for the Exodus address is required for Class B transactions, but not for Class C transactions. At this point there is not yet a nice way to create Class C transactions with OmniJ.

**Comment by msgilligan** [comment] 2019-01-08 17:53
So @cassc I'm going to close this as a duplicate of Issue [#120 Add support for Class C Omni transactions](https://github.com/OmniLayer/OmniJ/issues/120).

**Closed by msgilligan** 2019-01-08 17:53 UTC
