### ISSUE TITLE
 maven error,0.5.5 is invalid

### ISSUE THREAD

**Issue by initsysctrl** [OmniLayer/OmniJ#153] opened 2018-08-24 05:43 UTC
<dependency>
  <groupId>foundation.omni</groupId>
  <artifactId>omnij-cli</artifactId>
  <version>0.5.5</version>
  <type>pom</type>
</dependency>

show 0.5.5 is invalid, what should i do?

**Comment by msgilligan** [comment] 2018-08-24 19:30
Can you provide a little more detailed information, please?

**Comment by msgilligan** [comment] 2018-08-24 19:33
Also, this looks like a duplicate of #151

**Comment by msgilligan** [comment] 2021-09-28 23:39
Closing due to lack of information.

Note also that I've added a sample app (with a Maven build): https://github.com/OmniLayer/omnij-maven-sample

**Closed by msgilligan** 2021-09-28 23:39 UTC
