### ISSUE TITLE
How to build Class C transactions by Omnij

### ISSUE THREAD

**Issue by ruanqunfeng** [OmniLayer/OmniJ#147] opened 2018-06-20 11:58 UTC

**Comment by ruanqunfeng** [comment] 2018-06-20 12:00
@dexX7 Can you help me ?

**Comment by dexX7** [comment] 2018-06-27 11:00
Hi @ruanqunfeng, currently there is no handy way to build class C transactions with OmniJ.

But then again, please see (3) of this post for some direction:

https://github.com/OmniLayer/omnicore/issues/664#issuecomment-400630510

**Comment by msgilligan** [comment] 2018-07-11 15:30
This is a duplicate of #120

**Closed by msgilligan** 2018-07-11 15:30 UTC
